---
default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - name: yamlfix
        id: yamlfix
        entry: poetry run poe yamlfix
        language: system
      - name: ruff-lint
        id: ruff-lint
        entry: poetry run poe ruff-lint
        language: system
        types_or: [cython, pyi, python]
      - name: ruff-format
        id: ruff-format
        entry: poetry run poe ruff-format
        language: system
        types_or: [cython, pyi, python]
      - name: snakefmt
        id: snakefmt
        entry: poetry run poe snakefmt
        language: system
