---
name: Deploy packages
on:
  workflow_dispatch:
  push:
    tags: [v*]
jobs:
  deploy_docker:
    uses: khanlab/actions/.github/workflows/workflow-release_task-deployDocker.yml@v0.1.1
    with:
      maximize_space: true
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
