---
name: Release package
on:
  workflow_dispatch:
    inputs:
      comments:
        description: Comments
        required: false
jobs:
  release_package:
    uses: khanlab/actions/.github/workflows/workflow-release_task-publishGithub.yml@v0.3.5
    with:
      comments: ${{ github.event.inputs.comments }}
      pipeline-description: true
    secrets:
      BP_PAT: ${{ secrets.BP_PAT_TOKEN }}
